### ISSUE TITLE
Some questions about the code

### ISSUE THREAD

**Issue by haohang96** [NVlabs/ODISE#36]
Thank you for your outstanding work.

I have thoroughly reviewed the paper and the code. Most of it is clear and understandable.  However, I find the following sections rather perplexing: [self.alpha_cond](https://github.com/NVlabs/ODISE/blob/2b187e4b2ff4c3d5da342aec2cc234b537720a65/odise/modeling/meta_arch/ldm.py#L657) and [self.alpha_cond_time_embed](https://github.com/NVlabs/ODISE/blob/2b187e4b2ff4c3d5da342aec2cc234b537720a65/odise/modeling/meta_arch/ldm.py#L668C6-L668C6)

`self.alpha_cond = nn.Parameter(torch.zeros_like(self.ldm_extractor.ldm.uncond_inputs))`
`self.alpha_cond_time_embed = nn.Parameter(torch.zeros(self.ldm_extractor.ldm.unet.time_embed[-1].out_features))`

It appears that **self.alpha_cond** and **self.alpha_cond_time_embed** are used to interact with prefixes (as referenced [here](https://github.com/NVlabs/ODISE/blob/2b187e4b2ff4c3d5da342aec2cc234b537720a65/odise/modeling/meta_arch/ldm.py#L707)), which are generated by the Implicit Captioner. Subsequently, the results of this interaction are fed into the Latent Diffusion Model.

I'm curious about the necessity of the following operation (as mentioned [here](https://github.com/NVlabs/ODISE/blob/2b187e4b2ff4c3d5da342aec2cc234b537720a65/odise/modeling/meta_arch/ldm.py#L707-L709C1)):

`batched_inputs["cond_inputs"] = (self.ldm_extractor.ldm.uncond_inputs + torch.tanh(self.alpha_cond) * prefix_embed)`.

It seems that we could directly feed **prefix_embed** into the Latent Diffusion Model. I would like to understand the purpose and rationale behind introducing **self.alpha_cond** and **self.alpha_cond_time_embed**. Has any previous work employed such an operation?

I eagerly anticipate your response. Thank you very much.

**Comment by haohang96** [comment]
Thank you, @shalinidemello @xvjiarui , for your valuable contribution to this great work. I kindly request your advice regarding the aforementioned questions.

**Comment by xvjiarui** [comment]
Hi @haohang96 

Sorry for the late reply. 

The operation is not used very often in previous works. We use it to make diffusion features kind of conditioned on our input images.

**Comment by haohang96** [comment]
Thanks for your reply, I got it :)
