### ISSUE TITLE
Running equipment and running time

### ISSUE THREAD

**Issue by 123456klk1** [NVlabs/ODISE#4]
Hello, I have learned about your work. I feel really cool. I would like to ask, what is the running equipment and running time?

**Comment by KinGeorge** [comment]
In [Getting Started with ODISE
](https://github.com/NVlabs/ODISE/blob/main/GETTING_STARTED.md#command-line-based-training--evaluation), it says that ODISE trains in 6 days on 32 NVIDIA V100 GPUs.
But in the orignial paper's implementation details, it said that We use 16 V100 on coco_50e takes 2 days, so I'm a bit confused

**Comment by shalinidemello** [comment]
Experimental results in section 4.3 take takes 2 days on 16 V100 machines. To reproduce the results in section 4.2 takes 6 days on 32 V100 GPUs.
