### ISSUE TITLE
System RAM crashes while loading model in Google Colab

### ISSUE THREAD

**Issue by kaz12tech** [NVlabs/ODISE#9]
Thanks for the great Colab

I have a problems.
1. System RAM out of memory
When executing the code below, it overflows the system RAM and crashes.
I installed xformers, but I couldn't avoid it. Is there any solution?
> model = instantiate_odise(cfg.model)

**Comment by shalinidemello** [comment]
Are you running inference or training?

How much GPU memory do you have available on your system?

**Comment by kaz12tech** [comment]
I'm running demo.ipynb.
![image](https://user-images.githubusercontent.com/94593158/230656329-adcff76e-c0f5-4282-8ac1-cec00f0a9be1.png)

GPU is T4

**Comment by kaz12tech** [comment]
I was able to get around this by placing and garbage collecting the backbone immediately after instantiating it on the GPU and then instantiating the model.

**Comment by tejassp2002** [comment]
Hi @kaz12tech, I am facing the same issue. Can you please send the code of garbage collecting you used. 

@shalinidemello, any help on this would be appreciated. I am using default version of Colab, which has 12.7 GB of system RAM and T4 GPU. The session gets killed every time I try instantiating the model. 
One more thing, as a first step, I am only interested in semantic segmentation. So, any lead on that would also be helpful. 

I am trying to do inference. 
Thanks.
